from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time',    default_value='false'),
        DeclareLaunchArgument('path_topic',      default_value='/execute_path_plan'),
        DeclareLaunchArgument('cmd_vel_topic',   default_value='/cmd_vel'),
        DeclareLaunchArgument('execute_topic',   default_value='/execute_local_planner'),
        DeclareLaunchArgument('map_frame',       default_value='map'),
        DeclareLaunchArgument('robot_base_frame', default_value='base_footprint'),
        DeclareLaunchArgument('control_frequency',      default_value='20.0'),
        DeclareLaunchArgument('goal_tolerance',         default_value='0.15'),
        DeclareLaunchArgument('goal_yaw_tolerance',     default_value='0.05'),
        DeclareLaunchArgument('max_path_deviation',     default_value='0.3'),
        DeclareLaunchArgument('min_linear_velocity',    default_value='0.2'),
        DeclareLaunchArgument('max_linear_velocity',    default_value='0.5'),
        DeclareLaunchArgument('min_angular_velocity',   default_value='0.3'),
        DeclareLaunchArgument('max_angular_velocity',   default_value='1.0'),
        DeclareLaunchArgument('max_linear_acceleration',  default_value='0.5'),
        DeclareLaunchArgument('max_angular_acceleration', default_value='2.0'),
        DeclareLaunchArgument('holonomic',        default_value='true'),
        DeclareLaunchArgument('slowdown_distance', default_value='0.6'),
        DeclareLaunchArgument('lookahead_distance', default_value='0.5',
            description='Local target lookahead distance for heading scoring [m]'),
        # DWA-specific
        DeclareLaunchArgument('sim_time',       default_value='1.5',
            description='Trajectory simulation horizon [s]'),
        DeclareLaunchArgument('sim_granularity', default_value='0.05',
            description='Simulation time step [s]'),
        DeclareLaunchArgument('vx_samples',  default_value='10',
            description='Number of forward velocity samples'),
        DeclareLaunchArgument('vy_samples',  default_value='5',
            description='Number of lateral velocity samples (holonomic only)'),
        DeclareLaunchArgument('vth_samples', default_value='20',
            description='Number of angular velocity samples'),
        DeclareLaunchArgument('heading_bias', default_value='24.0',
            description='Weight for heading alignment score'),
        DeclareLaunchArgument('path_bias',    default_value='32.0',
            description='Weight for path following score'),
        DeclareLaunchArgument('speed_bias',   default_value='6.0',
            description='Weight for forward speed score'),
        DeclareLaunchArgument('ema_alpha',    default_value='0.4',
            description='EMA smoothing factor for velocity output (0=hold, 1=no filter)'),

        Node(
            package='machida_navigation',
            executable='dwa_local_planner',
            name='dwa_local_planner',
            output='screen',
            parameters=[{
                'use_sim_time':            LaunchConfiguration('use_sim_time'),
                'path_topic':              LaunchConfiguration('path_topic'),
                'cmd_vel_topic':           LaunchConfiguration('cmd_vel_topic'),
                'execute_topic':           LaunchConfiguration('execute_topic'),
                'map_frame':               LaunchConfiguration('map_frame'),
                'robot_base_frame':        LaunchConfiguration('robot_base_frame'),
                'control_frequency':       LaunchConfiguration('control_frequency'),
                'goal_tolerance':          LaunchConfiguration('goal_tolerance'),
                'goal_yaw_tolerance':      LaunchConfiguration('goal_yaw_tolerance'),
                'max_path_deviation':      LaunchConfiguration('max_path_deviation'),
                'min_linear_velocity':     LaunchConfiguration('min_linear_velocity'),
                'max_linear_velocity':     LaunchConfiguration('max_linear_velocity'),
                'min_angular_velocity':    LaunchConfiguration('min_angular_velocity'),
                'max_angular_velocity':    LaunchConfiguration('max_angular_velocity'),
                'max_linear_acceleration': LaunchConfiguration('max_linear_acceleration'),
                'max_angular_acceleration': LaunchConfiguration('max_angular_acceleration'),
                'holonomic':               LaunchConfiguration('holonomic'),
                'slowdown_distance':       LaunchConfiguration('slowdown_distance'),
                'lookahead_distance':      LaunchConfiguration('lookahead_distance'),
                'sim_time':                LaunchConfiguration('sim_time'),
                'sim_granularity':         LaunchConfiguration('sim_granularity'),
                'vx_samples':              LaunchConfiguration('vx_samples'),
                'vy_samples':              LaunchConfiguration('vy_samples'),
                'vth_samples':             LaunchConfiguration('vth_samples'),
                'heading_bias':            LaunchConfiguration('heading_bias'),
                'path_bias':               LaunchConfiguration('path_bias'),
                'speed_bias':              LaunchConfiguration('speed_bias'),
                'ema_alpha':               LaunchConfiguration('ema_alpha'),
            }],
        ),
    ])
