/**:
  ros__parameters:
    rgb_camera.color_profile: 640x480x30
    depth_module.depth_profile: 640x480x30

    # Flags
    enable_depth: true
    enable_color: true
    enable_infra1: false
    enable_infra2: false
    enable_fisheye1: false
    enable_fisheye2: false
    enable_gyro: true
    enable_accel: true
    enable_pose: true
    enable_sync: false
    tf_publish_rate: 0.0

    # Parameters that cannot be changed in runtime:
    serial_no: ""
    usb_port_id: ""
    device_type: ""
    reconnect_timeout: 6.0
    wait_for_device_timeout: -1.0
    rosbag_filename: ""
    initial_reset: false
    unite_imu_method: 2
    clip_distance: -1.0
    publish_tf: true
    diagnostics_period: 0.0

    # Post-Processing Filters
    align_depth.enable: true
    colorizer:
      enable: false\
    pointcloud__neon_:
      enable: true
      stream_filter: 2
      allow_no_texture_points: true
      ordered_pc: true 
      stream_index_filter: 0
    hdr_merge:
      enable: false

    # Other
    camera_name: "d455"
    json_file_path: ""
    gyro_fps: 200
    accel_fps: 200
    pose_fps: 200
