# Use internal network NTP server
server 192.168.123.161 iburst prefer

# If the network is not ready at startup, allow subsequent synchronization
makestep 1.0 3

# Allow hardware clock synchronization
rtcsync

# Logs (useful for debugging)
log tracking measurements statistics
logdir /var/log/chrony
