ARG ROS
FROM gai313/ros2:humble.aarch
ARG ROS

WORKDIR /ws/src
RUN apt-get update &&\
    apt-get install -y cmake g++ build-essential libyaml-cpp-dev libeigen3-dev net-tools &&\
    git clone https://github.com/unitreerobotics/unitree_sdk2.git

# Livox_SDK Install
WORKDIR /ws/src
RUN git clone https://github.com/GAI-313/livox_bringup.git &&\
    . /opt/ros/humble/setup.bash && vcs import . < livox_bringup/depend.repos &&\
    mv livox_ros_driver2/package_ROS2.xml livox_ros_driver2/package.xml &&\
    cd ./Livox-SDK2 && mkdir build && cd build && cmake .. && make -j && sudo make install &&\
    cd /ws/src/ && apt update && rosdep install -i -y --from-path . && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
RUN . /opt/ros/${ROS}/setup.bash &&\
    colcon build --symlink-install --cmake-args -DROS_EDITION="ROS2" -DHUMBLE_ROS=$ROS_DISTRO

CMD ["terminator"]
