[workspace]
authors = ["katana-2024-4 <roboworks@katana-2024-4>"]
channels = ["robostack-humble", "conda-forge"]
name = "g1_ws"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop-full = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
numpy = ">=1.26.4,<2"
python = ">=3.11.14,<3.12"
ros-humble-cartographer-ros-msgs = ">=2.0.9002,<3"
gcc = ">=15.2.0,<15.3"
gxx = ">=15.2.0,<15.3"
ros-humble-rosidl-generator-dds-idl = ">=0.8.1,<0.9"
ros-humble-pinocchio = ">=3.7.0,<4"
ros-humble-rmw-cyclonedds-cpp = ">=1.3.4,<2"
ros-humble-slam-toolbox = ">=2.6.10,<3"

[pypi-dependencies]
rustypot = ">=1.4.2, <2"

[activation.env]
RMW_IMPLEMENTATION="rmw_cyclonedds_cpp"
