uint8 TYPE_TTS = 0   # テキスト読み上げ
uint8 TYPE_WAV = 1   # WAVファイル再生

#uint8 volume 100
uint8 type 0          # 0: TTS, 1: WAV
string text          
string audio_path ""
---
bool success         
string message       
